#!/usr/bin/env bash

green() {
    tput setaf 2;
    cat;
    tput sgr0;
}

red() {
  tput setaf 1
  cat
  tput sgr0
}

assembly=$(coolc $1 -o /dev/stdout)

if [[ $? -ne 0 ]]; then 
    echo COMPILE FAILED | red 
    exit 1
fi

spim -file <(echo "$assembly") \
    | sed -e '1,5d' -e '/Increasing heap.../d' \
    | green
