#!/usr/bin/env bash

file_dir=$EXAMPLE_DIR/parser
file_cnt=$(ls $file_dir --sort size -r | grep cl$ | wc -l)
echo FOUND "$file_cnt" FILES
echo
./run_test $(\
    ls $file_dir --sort size -r | grep cl$ \
    | head -n ${1:-$file_cnt} \
    | sed 's@^@'"$file_dir"'/@'\
)