#!/usr/bin/env bash

file_cnt=$(ls $EXAMPLE_DIR/parser --sort size -r | grep cl$ | wc -l)
echo FOUND "$file_cnt" FILES
echo
./run_test $(\
    ls $EXAMPLE_DIR/parser --sort size -r | grep cl$ \
    | head -n ${1:-$file_cnt} \
    | sed 's@^@'"$EXAMPLE_DIR/parser"'/@'\
)