#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

green() {
    tput setaf 2;
    cat;
    tput sgr0;
}

blue() {
    tput setaf 4;
    cat;
    tput sgr0;
}

red() {
    tput setaf 1;
    cat;
    tput sgr0;
}

make parser

if [[ "$?" -ne 0 ]]; then
  echo "ERROR: make parser FAILED" | red
  exit 1
fi

for cl in "$@"; do
  input_cl=$cl
  echo
  echo "INPUT: ${input_cl}"
  echo "Comparing lexer output" | blue
  diff -u --color \
    --label mylexer <(mylexer $input_cl) \
    --label lexer <(lexer $input_cl)
  if [[ "$?" -eq 0 ]]; then
    echo PASS | green
  else
    echo FAILED | red
  fi

  echo "Comparing parser output" | blue
  diff -u --color \
    --label myparser <(mylexer $input_cl | myparser $input_cl) \
    --label parser <(lexer $input_cl | parser $input_cl)
  if [[ "$?" -eq 0 ]]; then
    echo PASS | green
  else
    echo FAILED | red
  fi
done
