#!/usr/bin/env bash

green() {
  tput setaf 2
  cat
  tput sgr0
}

blue() {
  tput setaf 4
  cat
  tput sgr0
}

red() {
  tput setaf 1
  cat
  tput sgr0
}

make parser

if [[ "$?" -ne 0 ]]; then
  echo "ERROR: make parser FAILED" | red
  exit 1
fi

for cl in "$@"; do
  input_cl=$cl
  echo
  echo "INPUT: ${input_cl}"
  if [[ ! -f "$input_cl" ]]; then
      echo FILE NOT FOUND | red
      continue;
  fi
  echo "Comparing lexer output" | blue
  diff -u --color \
    --label mylexer <(mylexer $input_cl) \
    --label lexer <(lexer $input_cl)
  if [[ "$?" -eq 0 ]]; then
    echo PASS | green
  else
    echo FAILED | red
  fi

  echo "Comparing parser output" | blue
  myoutput=$(mylexer $input_cl | myparser 2>&1)
  diff -U 6 --color \
    --label myparser <(echo "$myoutput") \
    --label parser <(lexer $input_cl | parser 2>&1)
  if [[ "$?" -eq 0 ]]; then
    echo PASS | green
  else
    echo FAILED | red
  fi
done
